<a href="https://colab.research.google.com/github/ptsnbkht/DI-Bootcamp/blob/main/w4d1daily_challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:

import numpy as np

# Create a random 5x5 matrix
matrix = np.random.rand(5, 5)

# Find the maximum value in the matrix
max_value = np.max(matrix)

# Replace the maximum value with 0
matrix[matrix == max_value] = 0

# Print the modified matrix
matrix

array([[0.52323673, 0.69349384, 0.70422849, 0.0113236 , 0.        ],
       [0.28926718, 0.37490034, 0.90303361, 0.14832092, 0.66717978],
       [0.68609685, 0.92980985, 0.63964152, 0.96062803, 0.74953207],
       [0.40018602, 0.28961042, 0.42250101, 0.97913632, 0.02137253],
       [0.58942594, 0.7597719 , 0.95809278, 0.71140358, 0.89899227]])

In [4]:

import numpy as np
array1 = np.random.rand(5)
array2 = np.random.rand(5)
common_values = np.intersect1d(array1, array2)
common_values

array([], dtype=float64)

In [5]:

import numpy as np
# Create a random 1D array of size 10
array_1d = np.random.rand(10)
print("Original array:", array_1d)
# Sort in ascending order
array_ascending = np.sort(array_1d)
print("Sorted in ascending order:", array_ascending)
# Sort in descending order
array_descending = np.sort(array_1d)[::-1]
print("Sorted in descending order:", array_descending)

Original array: [0.41103854 0.58860504 0.10275102 0.49492057 0.9192745  0.75484286
 0.18478045 0.04168311 0.96589928 0.11194923]
Sorted in ascending order: [0.04168311 0.10275102 0.11194923 0.18478045 0.41103854 0.49492057
 0.58860504 0.75484286 0.9192745  0.96589928]
Sorted in descending order: [0.96589928 0.9192745  0.75484286 0.58860504 0.49492057 0.41103854
 0.18478045 0.11194923 0.10275102 0.04168311]


In [6]:

import numpy as np
# Generate a random 4x4 matrix
matrix_4x4 = np.random.rand(4, 4)

# Find the rank of the matrix
rank = np.linalg.matrix_rank(matrix_4x4)

# Print the matrix and its rank
print("Random 4x4 matrix:\n", matrix_4x4)
print("\nRank of the matrix:", rank)

Random 4x4 matrix:
 [[0.26560721 0.76761229 0.12075421 0.20428345]
 [0.07238734 0.08959826 0.95601586 0.26143494]
 [0.85233798 0.03944604 0.14625783 0.18330952]
 [0.80098524 0.29416374 0.34651519 0.59189403]]

Rank of the matrix: 4


In [7]:

import numpy as np
n = 5 # You can change n to your desired size
result = np.ones((n, n), dtype=int)
result[1:-1, 1:-1] = 0
result

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])