<a href="https://colab.research.google.com/github/ptsnbkht/DI-Bootcamp/blob/main/w4d1xpexersise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

import numpy as np

# Create a 1D NumPy array
arr = np.arange(10)

# Print the array
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:

import numpy as np
my_list = [3.14, 2.17, 0, 1, 2]
numpy_array = np.array(my_list, dtype=int)
print(numpy_array)
```

SyntaxError: invalid syntax (<ipython-input-2-6faf2c44734c>, line 7)

In [3]:

import numpy as np
# Create a 3x3 NumPy array with values from 1 to 9
arr_3x3 = np.arange(1, 10).reshape(3, 3)

# Print the array
arr_3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:

import numpy as np
np.random.rand(4, 5)

array([[0.05609305, 0.18014518, 0.18395577, 0.44521554, 0.40362611],
       [0.93611335, 0.22912558, 0.81273522, 0.51411329, 0.6483185 ],
       [0.1532013 , 0.41778872, 0.13590529, 0.73769931, 0.42845469],
       [0.38127345, 0.55497194, 0.70781757, 0.12437065, 0.45990343]])

In [5]:

arr_3x3[1]

array([4, 5, 6])

In [6]:

import numpy as np
np.flip(arr)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [7]:

import numpy as np
identity_matrix = np.eye(4)
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:

import numpy as np
total_sum = np.sum(arr)
average = np.mean(arr)

print(f"Sum: {total_sum}")
print(f"Average: {average}")

Sum: 45
Average: 4.5


In [9]:

import numpy as np
# Create a NumPy array with elements from 1 to 20
arr_1_to_20 = np.arange(1, 21)

# Reshape the array into a 4x5 matrix
matrix_4x5 = arr_1_to_20.reshape(4, 5)

# Print the resulting matrix
matrix_4x5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [10]:

odd_numbers = arr[arr % 2 != 0]
odd_numbers

array([1, 3, 5, 7, 9])